"use client"

import React, { useContext } from 'react';
import Head from 'next/head';
import styles from '@/styles/pages/Token.module.css';
import TokenSection from '../token/TokenSection';
import FAQ from '@/components/section/FAQ';
import DAOSection from '@/components/section/DAOSection';
import TokenDistribution from '../token/distribution';
import TokenUseCase from '../token/useCase';
import Roadmap from '@/components/section/RoadmapCarousel';
import { faUserCheck, faFileContract, faCoins, faWallet, faFire, faClock } from '@fortawesome/free-solid-svg-icons';
import { faTelegram } from '@fortawesome/free-brands-svg-icons';
import StepByStep from '@/components/section/StepByStep';
import CrowdfundingSection from './CrowdfundingSection';
import { WalletContext } from '@/utils/WalletContext';
import VestingSection from './VestingSection';

const PreSeedPage = () => {
    const { walletAddress } = useContext(WalletContext);
    const crowdfundData = {
        type: "Pre-Seed",
        startDate: new Date('2024-09-01T00:00:00Z'), // September 1, 2024
        exchangeRate: 0.01, // Example exchange rate (1 TARA = 0.01 ETH)
        tvlDiscount: 5, // Example TVL discount percentage
        endDate: new Date('2024-09-15T00:00:00Z'), // Two weeks from September 1, 2024
        totalSupply: 300_000_000,
        sold: 50_000
    };



    const faqs = [
        {
            question: "What is the pre-seed phase?",
            answer: "The pre-seed phase is an early fundraising round where we offer a limited percentage of our tokens to early investors. This phase helps us raise initial capital to develop and grow the DeGym platform."
        },
        {
            question: "How much of the total token supply is allocated for the pre-seed phase?",
            answer: "We have allocated 3% of the total token supply for the pre-seed phase."
        },
        {
            question: "What is the price per token during the pre-seed phase?",
            answer: "The price per token during the pre-seed phase is set to reflect the potential future value of DeGym. This price aims to provide early investors with an opportunity to support our project at an advantageous rate."
        },
        {
            question: "What happens to the tokens that are not sold during the pre-seed phase?",
            answer: "Any tokens that are not sold during the pre-seed phase will be permanently burned, reducing the overall supply and potentially increasing the value of the remaining tokens."
        },
        {
            question: "Is there a vesting period for the pre-seed tokens?",
            answer: "Yes, there is a vesting period for the pre-seed tokens. This ensures that the tokens are gradually released to investors over time, helping to maintain the stability and growth of the DeGym ecosystem."
        },
        {
            question: "What happens if a team member leaves before the tokens are fully vested?",
            answer: "Tokens that are not yet vested will remain locked and may be reallocated or burned according to the project's governance rules."
        },
        {
            question: "Can I withdraw my tokens before they are vested?",
            answer: "No, tokens are locked until they are vested according to the schedule."
        },
        {
            question: "How can I track my vesting schedule?",
            answer: "You can track your vesting schedule through your vesting wallet, which will provide detailed information on the release of your tokens."
        },
        {
            question: "What is the next step after the pre-seed phase?",
            answer: "Following the pre-seed phase, we will conduct a pre-seed phase where we will offer 10% of the total token supply. The price per token during the pre-seed will be 10% higher than the price during the pre-seed phase."
        },
        {
            question: "How will the token price be adjusted after the pre-seed phase?",
            answer: "The token price will be adjusted based on the market cap accumulated during the pre-seed phase. This ensures that the token price reflects the value generated by early investments."
        },
        {
            question: "How can I participate in the pre-seed phase?",
            answer: "To participate in the pre-seed phase, you can visit our website and follow the instructions to invest. Make sure to join early to take advantage of this exclusive opportunity."
        },
    ];
    const howItWorksPreSeed = [
        {
            icon: faUserCheck,
            title: 'Purchase our Allium NFT',
            description: 'To be eligible for the pre-seed, purchase our Allium NFT.',
            link: 'https://allium-founders-pass.nfts2.me/',
            linkText: 'Mint Now'
        },
        {
            icon: faFileContract,
            title: 'Optional KYC',
            description: 'Fill out the form to participate in the DeGym pre-seed by providing your wallet address and NFT ID.',
            link: 'https://yk3osli6.forms.app/pre-seed-degym-project',
            linkText: 'Fill Form'
        },
        {
            icon: faTelegram,
            title: 'Join Our Telegram Group',
            description: 'Join our Telegram group to stay updated on the pre-seed and get community support.',
            link: 'https://t.me/degym_dao',
            linkText: 'Join Now'
        },
        {
            icon: faClock,
            title: 'Wait for Pre-Seed Start',
            description: 'The pre-seed start date is yet to be confirmed. Stay tuned for announcements in our Telegram group.'
        },
        {
            icon: faCoins,
            title: 'Purchase Tokens',
            description: 'During the pre-seed period, transact your TARA to the smart contract address (0x...) to purchase DGYM tokens.'
        },
        {
            icon: faWallet,
            title: 'Receive Tokens',
            description: 'After the pre-seed period ends, you will receive your DGYM tokens according to the vesting schedule.'
        },
        {
            icon: faFire,
            title: 'Burn Unsold Tokens',
            description: 'Any unsold tokens will be permanently burned, reducing the total supply and benefiting early investors.'
        }
    ];

    return (
        <>
            <Head>
                <title>DGYM Token - DeGym</title>
                <meta name="description" content="Learn more about the DGYM Token, its utility, and how it powers the DeGym ecosystem." />
            </Head>
            <main className={styles.main}>
                <section className={styles.hero}>
                    <div className="container mx-auto">
                        <h1>Invest In DeGym</h1>
                        <p className={styles.heroSubtitle}>Pre-Seed Opportunity: <b>Invest in Our Future, Share Our Success</b></p>
                        <button className="p-4 w-auto my-5"><a href='https://allium-founders-pass.nfts2.me/'>Get whitelisted</a></button>
                        <p className="max-w-3xl m-auto text-2xl">The DeGym project is embarking on a phased approach to raise funds and distribute tokens, ensuring <b>fair market valuation</b> and rewarding early investors.</p>
                    </div>
                </section>
                <section className="m-auto max-w-xl">
                    <CrowdfundingSection crowdfund={crowdfundData} walletAddress={walletAddress} />
                </section>
                <VestingSection />
                <TokenSection />
                <StepByStep steps={howItWorksPreSeed} title="How to <b>invest</b>?" />
                <TokenDistribution />
                <TokenUseCase />
                <DAOSection />
                <Roadmap />
                <FAQ faqs={faqs} />
            </main>
        </>
    );
};

export default PreSeedPage;
